### ISSUE TITLE
 Base.BaseGetExcel 缺少 write_excels  read_excels函数

### ISSUE THREAD

**Issue by Valuebai** [yzqyfly/Interface-Automation-Test#1]
下载老兄的代码，查看runner.py代码，发现这块报错，查看对应Base.BaseGetExcel ,缺少 write_excels  read_excels函数——麻烦老兄共享下完整的代码哈
from Base.BaseGetExcel import write_excels
from Base.BaseGetExcel import read_excels

**Comment by onlyQian** [comment]
@ 同求

**Comment by Valuebai** [comment]
> > 同求
> 
> > 下载老兄的代码，查看runner.py代码，发现这块报错，查看对应Base.BaseGetExcel，缺少write_excels read_excels函数 - 麻烦老兄共享下完整代码哈
> > 来自Base.BaseGetExcel
> > 从Base.BaseGetExcel导入write_excels导入read_excels
> 
> 修复了，是我runner.py里面调用的函数名写错了。这次应该可以了

还有个地方漏改了
./TestCases/Api.py
```python
from Base.BaseGetExcel import read_excels
——这个函数名称不存在的，应该改为：
from Base.BaseGetExcel import read_excels_data
```
