### ISSUE TITLE
第一次运行runner.py，报错

### ISSUE THREAD

**Issue by Valuebai** [yzqyfly/Interface-Automation-Test#2]
1. 修改Api.py中的read_excels为read_excels_data
```python
# from Base.BaseGetExcel import read_excels
from Base.BaseGetExcel import read_excels_data
```
2. 根据代码的账号密码，输入后执行

报错的信息如下：
```python 
C:\Python36\python.exe C:/mycode/Interface-Automation-Test/runner.py
创建文件成功
请输入登录URL:https://cloudapi.usr.cn/usrCloud/user/login
请输入账号:rj09
请输入密码:11da5e2caad4d291d16d60c62b0b43c6
正在请求令牌……
test_api (TestCases.Api.ApiTest) ... 异常中断,15秒后结束脚本
ERROR
正在生成聚合报告： C:\mycode\Interface-Automation-Test\Report\0_聚合报告.xlsx

======================================================================
ERROR: test_api (TestCases.Api.ApiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\mycode\Interface-Automation-Test\TestCases\Api.py", line 13, in test_api
    Config().config_req(ls, token)#将包含用例的列表和token传入请求模块config_req
  File "C:\mycode\Interface-Automation-Test\Base\BaseReq.py", line 147, in config_req
    if item["接口名"] == "$$$$$":#连续5个$，报告要分页，直接向数据文件中写入报告分页信息
TypeError: string indices must be integers

----------------------------------------------------------------------
Ran 1 test in 340.829s

FAILED (errors=1)
执行完毕！
=====请查阅控制台执行日志=====
```

**Comment by Valuebai** [comment]
需要大佬优化下代码呀，保证demo的可执行性

**Comment by Valuebai** [comment]
BaseRunner.py代码中提供的密码是错误的
```python
req = requests.session()
url = "https://cloudapi.usr.cn/usrCloud/user/login"  # 此处填写登录接口
data = {'account': 'rj09', 'password': '11da5e2caad4d291d16d60c62b0b43c6'}  # json格式输入用户名和密码。密码为MD5加密后

print("正在请求令牌……")

rps = req.post(url, json=data, verify=False)

print('111', rps.content)
print('222', rps.text)
print(rps.json()['data']['token'])  # 返回登录后的token

```

执行结果：

```python
正在请求令牌……
C:\Python36\lib\site-packages\urllib3\connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
111 b'{"data":"","info":"password is error","status":1000}'
222 {"data":"","info":"password is error","status":1000}
Traceback (most recent call last):
  File "C:/mycode/Interface-Automation-Test/Cases/test.py", line 31, in <module>
    print(rps.json()['data']['token'])  # 返回登录后的token
TypeError: string indices must be integers
```

**Comment by yzqyfly** [comment]
那个demo里面的密码是MD5加密以后的，加密前是啥我真忘了。后来更新代码加入了自动MD5加密功能。所以运行run.py脚本时输入的密码应该输入demo里面那个MD5解密后的明文密码。我近期重新整理一下代码。

**Comment by sobimask** [comment]
![image](https://user-images.githubusercontent.com/51392055/65479732-2c9c3580-dec1-11e9-9496-1ea5e6ea0d1b.png)

**Comment by sobimask** [comment]
这个怎么办啊 大佬

**Comment by yzqyfly** [comment]
> 这个怎么办啊 大佬

好像macOS会出这个问题

**Comment by yzqyfly** [comment]
> BaseRunner.py代码中提供的密码是错误的
> 
> ```python
> req = requests.session()
> url = "https://cloudapi.usr.cn/usrCloud/user/login"  # 此处填写登录接口
> data = {'account': 'rj09', 'password': '11da5e2caad4d291d16d60c62b0b43c6'}  # json格式输入用户名和密码。密码为MD5加密后
> 
> print("正在请求令牌……")
> 
> rps = req.post(url, json=data, verify=False)
> 
> print('111', rps.content)
> print('222', rps.text)
> print(rps.json()['data']['token'])  # 返回登录后的token
> ```
> 
> 执行结果：
> 
> ```python
> 正在请求令牌……
> C:\Python36\lib\site-packages\urllib3\connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> 111 b'{"data":"","info":"password is error","status":1000}'
> 222 {"data":"","info":"password is error","status":1000}
> Traceback (most recent call last):
>   File "C:/mycode/Interface-Automation-Test/Cases/test.py", line 31, in <module>
>     print(rps.json()['data']['token'])  # 返回登录后的token
> TypeError: string indices must be integers
> ```

明文账号是：rj09
明文密码是：123456

**Comment by yzqyfly** [comment]
> BaseRunner.py代码中提供的密码是错误的
> 
> ```python
> req = requests.session()
> url = "https://cloudapi.usr.cn/usrCloud/user/login"  # 此处填写登录接口
> data = {'account': 'rj09', 'password': '11da5e2caad4d291d16d60c62b0b43c6'}  # json格式输入用户名和密码。密码为MD5加密后
> 
> print("正在请求令牌……")
> 
> rps = req.post(url, json=data, verify=False)
> 
> print('111', rps.content)
> print('222', rps.text)
> print(rps.json()['data']['token'])  # 返回登录后的token
> ```
> 
> 执行结果：
> 
> ```python
> 正在请求令牌……
> C:\Python36\lib\site-packages\urllib3\connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> 111 b'{"data":"","info":"password is error","status":1000}'
> 222 {"data":"","info":"password is error","status":1000}
> Traceback (most recent call last):
>   File "C:/mycode/Interface-Automation-Test/Cases/test.py", line 31, in <module>
>     print(rps.json()['data']['token'])  # 返回登录后的token
> TypeError: string indices must be integers
> ```

好像macOS会出这个问题
